//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance_DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelationDetail
    {
        public int Id { get; set; }
        public int EmpId { get; set; }
        public int RelationTypeId { get; set; }
        public string RelationName { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual RelationType RelationType { get; set; }
    }
}
